const contactTypes = {
	START_POST_CONTACT: 'START_POST_CONTACT',
	SUCCESS_POST_CONTACT: 'SUCCESS_POST_CONTACT',
	FAIL_POST_CONTACT: 'FAIL_POST_CONTACT',
	
	START_FETCH_CONTACT: "START_FETCH_CONTACT",
	SUCCESS_FETCH_CONTACT: "SUCCESS_FETCH_CONTACT",
	FAIL_FETCH_CONTACT: "FAIL_FETCH_CONTACT",
	
	START_DELETE_CONTACT: "START_DELETE_CONTACT",
	SUCCESS_DELETE_CONTACT: "SUCCESS_DELETE_CONTACT",
	FAIL_DELETE_CONTACT: "FAIL_DELETE_CONTACT",
}

export default contactTypes