const bookTypes = {
	START_BOOK_SERVICE: 'START_BOOK_SERVICE',
	SUCCESS_BOOK_SERVICE: 'SUCCESS_BOOK_SERVICE',
	FAIL_BOOK_SERVICE: 'FAIL_BOOK_SERVICE',

	START_EDIT_BOOK_SERVICE: 'START_EDIT_BOOK_SERVICE',
	SUCCESS_EDIT_BOOK_SERVICE: 'SUCCESS_EDIT_BOOK_SERVICE',
	FAIL_EDIT_BOOK_SERVICE: 'FAIL_EDIT_BOOK_SERVICE',
	
	START_FETCH_BOOK_SERVICE: "START_FETCH_BOOK_SERVICE",
	SUCCESS_FETCH_BOOK_SERVICE: "SUCCESS_FETCH_BOOK_SERVICE",
	FAIL_FETCH_BOOK_SERVICE: "FAIL_FORGOT_PASSWORD",
	
	START_DELETE_BOOK: "START_DELETE_BOOK",
	SUCCESS_DELETE_BOOK: "SUCCESS_DELETE_BOOK",
	FAIL_DELETE_BOOK: "FAIL_DELETE_BOOK",
	
	LOGOUT_USER: 'LOGOUT_USER',
}

export default bookTypes