const bookTypes = {
	START_POST_BOOK_SERVICE: 'START_POST_BOOK_SERVICE',
	SUCCESS_POST_BOOK_SERVICE: 'SUCCESS_POST_BOOK_SERVICE',
	FAIL_POST_BOOK_SERVICE: 'FAIL_POST_BOOK_SERVICE',
	
	START_FETCH_BOOK_SERVICE: "START_FETCH_BOOK_SERVICE",
	SUCCESS_FETCH_BOOK_SERVICE: "SUCCESS_FETCH_BOOK_SERVICE",
	FAIL_FETCH_BOOK_SERVICE: "FAIL_FETCH_BOOK_SERVICE",
	
	START_DELETE_BOOK: "START_DELETE_BOOK",
	SUCCESS_DELETE_BOOK: "SUCCESS_DELETE_BOOK",
	FAIL_DELETE_BOOK: "FAIL_DELETE_BOOK",
}

export default bookTypes